
spring.application.name=HidraTrack

spring.datasource.url=jdbc:mysql://localhost:3306/hidratrack_db
spring.datasource.username=root
spring.datasource.password=HalwkGMD07,pedro

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect